# -*- coding: utf-8 -*-
"""Kel5_webScrapping_proses.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a0XYrCNvbZsgUWPjQhDgu5Ig995lJdr2
"""

!python --version

!apt-get update

!pip install selenium

!apt-get install -y chromium-browser

!apt install chromium-chromedriver

from selenium import webdriver

from selenium.webdriver.chrome.service import Service

!ls /usr/lib/chromium-browser

def web_driver():
  options = webdriver.ChromeOptions()
  options.add_argument('--verbose')
  options.add_argument('--no-sandbox')
  options.add_argument('--headless')
  options.add_argument('--disable-gpu')
  options.add_argument('--window-size=1920, 1200')
  options.add_argument('--disable-dev-shm-usage')
  driver = webdriver.Chrome(options=options)
  return driver

driver = web_driver()

driver.get("https://shop.googlemerchandisestore.com/Google+Redesign/Google+Out+of+this+World+Socks")

import time

import pandas as pd
from selenium import webdriver
from bs4 import BeautifulSoup

driver.get("https://shop.googlemerchandisestore.com/Google+Redesign/Women+Techmakers+Tote")

time.sleep(15)

html = driver.page_source # Get HTML file from Selenium
soup = BeautifulSoup(html, "html.parser") # Parse HTML source using Beautiful Soup, so we can use further

price = soup.find("span", {"id": "js-item-pricedollar-9213874"}).text
product_name = soup.find("h3", {"class": "itemTitle"}).text #prodImg
product_image_url = soup.select('#prodImg img')[1]['src']
available = soup.find('div', class_='f-field').text
SKU = soup.find("p", class_="tab-pane active fade show")
details = soup.find("div", class_='tab-pane active fade show').text


result = [{
    "price" : price,
    "product_name": product_name,
    "product_image_url": product_image_url,
    "available" : available,
    "SKU" : SKU,
    "details" : details
}]

result_df = pd.DataFrame(result)
result_df.to_csv('kel5_webScrap_result.csv', index=False)